## Append samples you want in your CSV to this file as resources ##
resources:
- appstudio.redhat.com_v1alpha1_controller.yaml
- appstudio.redhat.com_v1beta1_imagerepository.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
